HW2 done
Liliya-Mironova/2018-FS-11-Frontend-Mironova pull request #3
Opened 2018-10-17 21:09 UTC by Liliya-Mironova

- Styles in the form added

2018-10-18 16:36 UTC, martinkomitsky requested changes
Не сделано задание про `getReadableSize(100000); //"98 Кбайт"`

2018-10-18 20:46 UTC, Liliya-Mironova commented
- Чуть улучшила стиль формы отправки сообщений

- Сделала пункт про getReadableSize(100000);

2018-10-20 18:44 UTC, martinkomitsky approved these changes

2018-10-20 18:44 UTC, merged

2018-10-20 18:44 UTC, martinkomitsky commented
OK, в этот раз без штрафа. Но в следующий раз высылай полностью готовое ДЗ, а не только часть.
10