HW3: message list and custom event, file loading, drag-and-drop added
Liliya-Mironova/2018-FS-11-Frontend-Mironova pull request #4
Opened 2018-10-25 16:33 UTC by Liliya-Mironova

- Сделано добавление сообщений в список.
Проблемы:
1. если делать ul "display: flex; flex-direction: column-reverse;", то новые сообщения появляются внизу, но список расползается по всей ширине.
2. пока не сообразила, как очищать форму после отправки сообщения
- Обработана отправка пустого сообщения if (li.innerText.length > 2)  { ..addendChild() }
- Добавлена обработка файлов через FileList:
1) при загрузке информация о файле отправляется как текстовое сообщение
2) изображения - если тип файла соответствует "image/.*" - пока не сумела добавить в список
- Реализовано drag&drop на отдельном элементе. Это работает, но в консоли вылетает ошибка  "index.js:102 Uncaught TypeError: Cannot read property 'name' of undefined at HTMLElement._onDragOver (index.js:102)"
- Информация о местоположении пока не доюавлена

2018-10-30 19:22 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/47744203-d7947700-dc91-11e8-8107-0d5a586091a2.png)
1. Не смог кликнуть на кнопку с геопозицией, пока не выставил ей css `z-index: 555`. 
2. Drag and drop работает, но показывается только имя. В задании требовалось добавить предпросмотр.
3. При D&D выпадает в консоли такая ошибка. Ее надо тоже исправить

Доделай это, пожалуйста, тут еще можно получить максимум!

2018-10-30 19:22 UTC, martinkomitsky commented on src/lib/components/message-form/index.js
> +		event.stopPropagation();
Зачем тут это? Очень опасный метод, надо пользоваться с умом. Есть понимание, зачем это тут сейчас и как без него обойтись?

2018-11-01 20:41 UTC, Liliya-Mironova commented
Добрый вечер, Мартин. 
Большое спасибо за замечания (особенно за z-index).

- Добавила отправку изображений, как через кнопку, так и через D&D;

- Починила D&D, перенесла его со странной таблички на всё окно;

- Добавила очистку формы отправки сообщения после нажатия на Enter;

- Поменяла стили.

2018-11-04 07:18 UTC, martinkomitsky commented
Добрый день, Лилия.

Спасибо за исправления.

2018-11-04 07:18 UTC, martinkomitsky approved these changes

2018-11-04 07:18 UTC, merged

2018-11-04 07:18 UTC, martinkomitsky commented
10