HW5: new react app from empty created
Liliya-Mironova/2018-FS-11-Frontend-Mironova pull request #8
Opened 2018-11-17 11:52 UTC by Liliya-Mironova

Мартин, здравствуйте.

- Переписала React-приложение с нуля. Не работают пока только две вещи: очистка формы отправки сообщения (хотя это вроде бы прописано: 
_onSubmit (event) {
...
event.target.value = '';
...
}

- Ещё не придумала, как организовать появление значка отправки и времени в сообщении при достаке на сервер.

2018-11-17 12:09 UTC, Liliya-Mironova commented
- Ещё есть костыль в виде лишей мнимой кнопки в FormInput, я его поправлю.

2018-11-17 13:48 UTC, Liliya-Mironova commented
- Привязала к кнопкам картинки, но опять же они ищутся в localhost:5000/path-to-image

- Отправка сообщения работает при нажатии на кнопку отправки, так и при нажатии на Enter

2018-11-17 13:58 UTC, martinkomitsky requested changes
> * _onSubmit (event) {
>   ...
>   event.target.value = '';
>   ...
>   }

Помни, что для взаимодействия с отображением, в React мы оперируем сменой состояния. 

1. Все свои компоненты перенеси в папку `src/components`, чтобы не было бардака в репозитории
2. Из своей функции sendToServer надо возвращать промис, который возвращает Fetch, то есть, надо написать `return fetch ('http://127.0.0.1:8082/message',`. Это тебе даст возможность асинхронного вызова функций после успешной отправки сообщения. Например, можно будет сделать так (очень примерный код, который может тебя натолкнуть на мысли):
```
sendToServer.then(response => {
  this.setState({
    [response.messageId]: 'delivered'
  });
});
```
3. Для очистки формы надо использовать `setState`. Твой input сейчас не использует state совсем. Должно быть вот так:
```
<input className="Input"
   placeholder="Введите сообщение"
   onChange={this._onInput.bind(this)}
   value={ this.state.val }
/>
```
4. event.target.value больше не нужен, мы им не пользуемся
5. Исправь ошибки линтера
![image](https://user-images.githubusercontent.com/14847018/48661870-02503f00-ea8a-11e8-9de4-b7f25d16dae9.png)

2018-11-18 14:04 UTC, Liliya-Mironova commented
Спасибо за замечания.

- Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (at FormInput.js:29)
<input className="Input" 
                       placeholder="Введите сообщение"
                       value={this.state.text} />
Здесь и placeholder и value нужны, с defaultvalue ничего не работает. Если выносить обработчик onChange в отдельную функцию, то непонятно, что в ней делать.

- Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

     Я понимаю, что вызов this.setState({}) в render() приводит к зацикливанию, поэтому выношу этот вызов в отдельную функцию sendAndUpdate(text, file), в которой обрабатываю переходы между состояниями, чтобы зацикливания не случалось. Ну очень нужно менять состояние уже отрисованного сообщения после доставки на сервер.
Думала делать отправку сообщения из родительского элемента (MessageList), тогда всё равно придётся вызывать setState из render() теперь у него, и передавать через properties всё в Message.

2018-11-22 08:50 UTC, Liliya-Mironova commented
- Сделала роутинг, но из-за нового div'а окно для сообщений съехало вправо и вниз. Может, раз у нас одностраничное приложение для ноутбука, стоит сделать меню с диалогами, как у Телеграмма - постоянным и находящимся слева? Так будет удобнее перемещаться между страницами и стили не поедут.

2018-11-25 00:24 UTC, Liliya-Mironova commented
Ещё я переделала логику потока данных и преписала всё на Redux. Реализовала всё, кроме обновления статуса отправки. Могу закоммитить сюда же. В HW7 я:

избавилась от этого warning'а, написав onChange вместо onInput:
> * Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
>   in input (at FormInput.js:29)

А этот исчез в результаты смены логики:
> * Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

2018-11-25 11:44 UTC, martinkomitsky approved these changes

2018-11-25 11:44 UTC, merged

2018-11-25 11:44 UTC, martinkomitsky commented
коммить, пожалуйта, каждое дз в отдельную ветку